run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
